swagger: '2.0'
info:
  description: >
    Copyright (c) 2019 InterDigital Communications, Inc.
    All rights reserved.
    The information provided herein is the proprietary and confidential information of InterDigital Communications, Inc.
  version: 1.0.0
  title: MEEP Model
definitions:
  NodeServiceMaps:
    type: object
    properties:
      node:
        type: string
        description: Unique external node identifier
      ingressServiceMap:
        type: array
        items:
          $ref: '#/definitions/IngressService'
      egressServiceMap:
        type: array
        items:
          $ref: '#/definitions/EgressService'
    description: Node-specific mapping of exposed internal & external services
    example: {}
  Deployment:
    type: object
    properties:
      interDomainLatency:
        type: integer
        description: Latency in ms between domains
      interDomainLatencyVariation:
        type: integer
        description: Latency variation in ms between domains
      interDomainThroughput:
        type: integer
        description: The limit of the traffic supported between domains
      interDomainPacketLoss:
        type: number
        format: double
        description: Packet lost (in terms of percentage) between domains
      meta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      userMeta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      domains:
        type: array
        items:
          $ref: '#/definitions/Domain'
    description: Network deployment object
    example: {}
  Domain:
    type: object
    properties:
      id:
        type: string
        description: Unique domain ID
      name:
        type: string
        description: Domain name
      type:
        type: string
        description: Domain type
        enum:
          - OPERATOR
          - PUBLIC
      interZoneLatency:
        type: integer
        description: Latency in ms between zones within domain
      interZoneLatencyVariation:
        type: integer
        description: Latency variation in ms between zones within domain
      interZoneThroughput:
        type: integer
        description: The limit of the traffic supported between zones within the domain
      interZonePacketLoss:
        type: number
        format: double
        description: Packet lost (in terms of percentage) between zones within the domain
      meta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      userMeta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      zones:
        type: array
        items:
          $ref: '#/definitions/Zone'
    description: Operator domain object
    example: {}
  EgressService:
    type: object
    properties:
      name:
        type: string
        description: Service name
      meSvcName:
        type: string
        description: Multi-Edge service name, if any
      ip:
        type: string
        description: External node IP address 
      port:
        type: integer
        description: Service port number
      protocol:
        type: string
        description: Service protocol (TCP or UDP)
    description: External service exposed internally via specific port
  Event:
    type: object
    properties:
      name:
        type: string
        description: Event name
      type:
        type: string
        description: Event type
        enum:
          - NETWORK-CHARACTERISTICS-UPDATE
          - UE-MOBILITY
          - POAS-IN-RANGE
          - OTHER
      eventNetworkCharacteristicsUpdate:
        $ref: '#/definitions/EventNetworkCharacteristicsUpdate'
      eventUeMobility:
        $ref: '#/definitions/EventUeMobility'
      eventPoasInRange:
        $ref: '#/definitions/EventPoasInRange'
      eventOther:
        $ref: '#/definitions/EventOther'
    description: Event object
    example:
      name: name
      type: UE-MOBILITY
      eventUeMobility:
        ue: ue
        dest: dest
  EventList:
    type: object
    properties:
      events:
        type: array
        items:
          $ref: '#/definitions/Event'
    description: Event list object
    example:
  EventNetworkCharacteristicsUpdate:
    type: object
    properties:
      elementName:
        type: string
        description: Name of the network element to be updated
      elementType:
        type: string
        description: Type of the network element to be updated
        enum:
          - OPERATOR
          - POA
          - SCENARIO
          - ZONE-INTER-EDGE
          - ZONE-INTER-FOG
          - ZONE-EDGE-FOG
      latency:
        type: integer
        description: Latency in ms
      latencyVariation:
        type: integer
        description: Latency variation in ms
      throughput:
        type: integer
        description: Throughput limit
      packetLoss:
        type: number
        format: double
        description: Packet loss percentage
    description: Network Characteristics update Event object
    example: {}
  EventPoasInRange:
    type: object
    properties:
      ue:
        type: string
        description: UE identifier
      poasInRange:
        type: array
        items:
          type: string
          description: POAs visible to UE
    description: POAs In Range Event object
    example:
      ue: ue
      poasInRange:
        - poa1
        - poa2
  EventUeMobility:
    type: object
    properties:
      ue:
        type: string
        description: UE identifier
      dest:
        type: string
        description: Destination identifier
    description: UE Mobility Event object
    example:
      ue: ue
      dest: dest
  EventOther:
    type: object
    properties:
      event:
        type: string
        description: Other event string
    description: Other Event object
    example:
      event: event
  ExternalConfig:
    type: object
    properties:
      ingressServiceMap:
        type: array
        items:
          $ref: '#/definitions/IngressService'
      egressServiceMap:
        type: array
        items:
          $ref: '#/definitions/EgressService'
    description: |-
      External Process configuration.
      NOTE: Only valid if 'isExternal' is set.
    example: {}
  GpuConfig:
    type: object
    properties:
      type:
        type: string
        description: Requested GPU type
      count:
        type: integer
        description: Number of GPUs requested
    description: GPU configuration object
  IngressService:
    type: object
    properties:
      name:
        type: string
        description: Service name (unique or multi-edge)
      port:
        type: integer
        description: Internal service port number
      externalPort:
        type: integer
        description: Externally-exposed unique service port in range (30000 - 32767)
      protocol:
        type: string
        description: Service protocol (TCP or UDP)
    description: Internal service exposed externally via specific port
  NetworkLocation:
    type: object
    properties:
      id:
        type: string
        description: Unique network location ID
      name:
        type: string
        description: Network location name
      type:
        type: string
        description: Network location type
        enum:
          - POA
          - DEFAULT
      terminalLinkLatency:
        type: integer
        description: Latency in ms for all terminal links within network location
      terminalLinkLatencyVariation:
        type: integer
        description: Latency variation in ms for all terminal links within network location
      terminalLinkThroughput:
        type: integer
        description: The limit of the traffic supported for all terminal links within the network location
      terminalLinkPacketLoss:
        type: number
        format: double
        description: Packet lost (in terms of percentage) for all terminal links within the network location
      meta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      userMeta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      physicalLocations:
        type: array
        items:
          $ref: '#/definitions/PhysicalLocation'
    description: Logical network location object
    example: {}
  PhysicalLocation:
    type: object
    properties:
      id:
        type: string
        description: Unique physical location ID
      name:
        type: string
        description: Physical location name
      type:
        type: string
        description: Physical location type
        enum:
          - UE
          - FOG
          - EDGE
          - CN
          - DC
      isExternal:
        type: boolean
        description: |-
          true: Physical location is external to MEEP
          false: Physical location is internal to MEEP
      networkLocationsInRange:
        type: array
        items:
          type: string
          description: Names of network locations within range of physical location
      meta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      userMeta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      processes:
        type: array
        items:
          $ref: '#/definitions/Process'
    description: Physical location object
    example: {}
  PodStatus:
    type: object
    properties:
      name:
        type: string
        description: Pod name
      namespace:
        type: string
        description: Pod namespace
      meepApp:
        type: string
        description: Pod process name
      meepOrigin:
        type: string
        description: 'Pod origin(core, scenario)'
      meepScenario:
        type: string
        description: Pod scenario name
      phase:
        type: string
        description: Pod phase
      podInitialized:
        type: string
        description: Pod initialized (true/false)
      podReady:
        type: string
        description: Pod ready (true/false)
      podScheduled:
        type: string
        description: Pod scheduled (true/false)
      podUnschedulable:
        type: string
        description: Pod unschedulable (true/false)
      podConditionError:
        type: string
        description: Pod error message
      containerStatusesMsg:
        type: string
        description: Failed container error message
      nbOkContainers:
        type: string
        description: Number of containers that are up
      nbTotalContainers:
        type: string
        description: Number of total containers in the pod
      nbPodRestart:
        type: string
        description: Number of container failures leading to pod restarts
      logicalState:
        type: string
        description: State that is mapping the kubernetes api state
      startTime:
        type: string
        description: Pod creation time
    example:
      podStatus:
        - podName: mypod
          namespace: default
          meepApp: pod1
          meepOrigin: scenario
          meepScenario: myScenario
          phase: Running
          podInitialized: 'True'
          podReady: 'False'
          podScheduled: 'True'
          podUnschedulable: 'False'
          podConditionError: 'containers with unready status: [myshel]'
          containerStatusesMsg: null
          nbOkContainers: '0'
          nbTotalContainers: '1'
          nbPodRestart: '15005'
          startTime: '2018-09-10 14:24:00 +0000 UTC'
  PodsStatus:
    type: object
    properties:
      podStatus:
        type: array
        items:
          $ref: '#/definitions/PodStatus'
    description: List of all pods status
    example: {}
  Process:
    type: object
    properties:
      id:
        type: string
        description: Unique process ID
      name:
        type: string
        description: Process name
      type:
        type: string
        description: Process type
        enum:
          - UE-APP
          - EDGE-APP
          - MEC-SVC
          - CLOUD-APP
      isExternal:
        type: boolean
        description: |-
          true: process is external to MEEP
          false: process is internal to MEEP
      image:
        type: string
        description: Docker image to deploy inside MEEP
      environment:
        type: string
        description: 'Environment variables using the format NAME="value",NAME="value",NAME="value"'
      commandArguments:
        type: string
        description: Arguments to command executable
      commandExe:
        type: string
        description: Executable to invoke at container start up
      serviceConfig:
        $ref: '#/definitions/ServiceConfig'
      gpuConfig:
        $ref: '#/definitions/GpuConfig'
      externalConfig:
        $ref: '#/definitions/ExternalConfig'
      status:
        type: string
        description: Process status
      userChartLocation:
        type: string
        description: Chart location for the deployment of the chart provided by the user
      userChartAlternateValues:
        type: string
        description: Chart values.yaml file location for the deployment of the chart provided by the user
      userChartGroup:
        type: string
        description: Chart supplemental information related to the group (service)
      meta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      userMeta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
    description: Application or service object
    example: {}
  Release:
    type: object
    properties:
      name:
        type: string
        description: Release name
      state:
        type: string
        description: Current release state
    example:
      name: name
      state: state
  Scenario:
    type: object
    properties:
      name:
        type: string
        description: Unique scenario name
      config:
        $ref: '#/definitions/ScenarioConfig'
      deployment:
        $ref: '#/definitions/Deployment'
    description: Scenario object
    example: {}
  ScenarioConfig:
    type: object
    properties:
      visualization:
        type: string
        description: Visualization configuration
      other:
        type: string
        description: Other scenario configuration
    description: Scenario configuration
    example:
      visualization: visualization
      other: other
  ScenarioList:
    type: object
    properties:
      scenarios:
        type: array
        items:
          $ref: '#/definitions/Scenario'
    description: Scenario list object
    example: {}
  ServiceConfig:
    type: object
    properties:
      name:
        type: string
        description: Unique service name
      meSvcName:
        type: string
        description: Multi-Edge service name, if any
      ports:
        type: array
        items:
          $ref: '#/definitions/ServicePort'
    description: Service object
    example: {}
  ServicePort:
    type: object
    properties:
      protocol:
        type: string
        description: Protocol that the application is using (TCP or UDP)
      port:
        type: integer
        description: Port number that the service is listening on
      externalPort:
        type: integer
        description: |
          External port number on which to expose the application (30000 - 32767)  <li>Only one application allowed per external port <li>Scenario builder must configure to prevent conflicts
    description: Service port object
    example: {}
  Settings:
    type: object
    description: MEEP settings - Key/Value Pair Map (string, string)
    additionalProperties:
      type: string
  Zone:
    type: object
    properties:
      id:
        type: string
        description: Unique zone ID
      name:
        type: string
        description: Zone name
      type:
        type: string
        description: Zone type
        enum:
          - ZONE
          - COMMON
      interFogLatency:
        type: integer
        description: Latency in ms between fog nodes (or PoAs) within zone
      interFogLatencyVariation:
        type: integer
        description: Latency variation in ms between fog nodes (or PoAs) within zone
      interFogThroughput:
        type: integer
        description: The limit of the traffic supported between fog nodes (or PoAs) within the zone
      interFogPacketLoss:
        type: number
        format: double
        description: Packet lost (in terms of percentage) between fog nodes (or PoAs) within the zone
      interEdgeLatency:
        type: integer
        description: Latency in ms between edge nodes within zone
      interEdgeLatencyVariation:
        type: integer
        description: Latency variation in ms between edge nodes within zone
      interEdgeThroughput:
        type: integer
        description: The limit of the traffic supported between edge nodes within the zone
      interEdgePacketLoss:
        type: number
        format: double
        description: Packet lost (in terms of percentage) between edge nodes within the zone
      edgeFogLatency:
        type: integer
        description: Latency in ms between fog nodes (or PoAs) and edge nodes within zone
      edgeFogLatencyVariation:
        type: integer
        description: Latency variation in ms between fog nodes (or PoAs) and edge nodes within zone
      edgeFogThroughput:
        type: integer
        description: The limit of the traffic supported between fog nodes (or PoAs) and edge nodes within the zone
      edgeFogPacketLoss:
        type: number
        format: double
        description: Packet lost (in terms of percentage) between fog nodes (or PoAs) and edge nodes within the zone
      meta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      userMeta:
        type: object
        description: Key/Value Pair Map (string, string)
        additionalProperties:
          type: string
      networkLocations:
        type: array
        items:
          $ref: '#/definitions/NetworkLocation'
    description: Logical zone (MEC network) object
    example: {}
