{{- if .Values.altIngress.enabled -}}
{{- $fullName := include "grafana.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.altIngress.path -}}
{{- $extraPaths := .Values.altIngress.extraPaths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-alt
  namespace: {{ template "grafana.namespace" . }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.altIngress.labels }}
{{ toYaml .Values.altIngress.labels | indent 4 }}
{{- end }}
{{- with .Values.altIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.altIngress.tls }}
  tls:
{{ toYaml .Values.altIngress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range $host := .Values.altIngress.hosts }}
    - http:
        paths:
{{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
      {{- if $host }}
      host: {{ $host }}
      {{- end }}
  {{- end }}
{{- end }}
