# Default values for meep-gis-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-gis-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
          
image:
  repository: meep-docker-registry:30001/meep-gis-engine
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}
    
service:
  name: meep-gis-engine
  type: ClusterIP
  port: 80

codecov:
  enabled: false
  
meepOrigin: core
