swagger: '2.0'
info:
  description: This is the MEEP Demo App API
  version: 0.0.1
  title: MEEP Demo App API
  termsOfService: InterDigital Internal Only
host: '127.0.0.1:8086'
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
parameters:
  Path.UeId:
    name: ueId
    in: path
    description: 'Identity of a ue, refered to as ue id'
    required: true
    type: string
  event:
    name: event
    in: body
    description: Mobility Group event notification
    required: true
    schema:
      $ref: '#/definitions/MobilityGroupEvent'
    x-exportParamName: event
tags:
  - name: Edge App Info
  - name: UE State
  - name: State Transfer
paths:
  /edge-app:
    get:
      tags:
        - Edge App Info
      summary: Retrieve edge add info
      description: ''
      operationId: getEdgeInfo
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EdgeInfo'
        '404':
          description: Not found
  '/ue/{ueId}':
    get:
      tags:
        - UE State
      summary: Retrieves the UE state values
      description: ''
      operationId: getUeState
      produces:
        - application/json
      parameters:
        - name: ueId
          in: path
          description: UE identifier
          required: true
          type: string
          x-exportParamName: UeId
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UeState'
        '400':
          description: Bad request
        '404':
          description: Not found
    post:
      tags:
        - UE State
      summary: Registers the UE and starts a counter
      description: ''
      operationId: createUeState
      produces:
        - application/json
      parameters:
        - name: ueId
          in: path
          description: UE identifier
          required: true
          type: string
          x-exportParamName: UeId
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Intenal server error
  /mg/event:
    post:
      tags:
        - State Transfer
      summary: Send event notification to registered Mobility Group Application
      description: ''
      operationId: handleEvent
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/event'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
definitions:
  EdgeInfo:
    type: object
    properties:
      svc:
        type: string
        description: Edge app service
      name:
        type: string
        description: Edge app local name
      ip:
        type: string
        description: IP address where the local edge app reside
    description: Edge app basic information object
    example:
      edgeInfo:
        - svc: game
          name: edge1-zone1-game
          ip: 10.32.0.13
  MobilityGroupAppState:
    type: object
    properties:
      ueId:
        type: string
        description: Mobility Group UE Identifier
      ueState:
        type: string
        description: Mobility Group Application State for provided UE
    description: Mobility Group Application State
  MobilityGroupEvent:
    type: object
    properties:
      name:
        type: string
        description: Mobility Group event name
      type:
        type: string
        description: Mobility Group event type
        enum:
          - STATE-UPDATE
          - STATE-TRANSFER-START
          - STATE-TRANSFER-COMPLETE
          - STATE-TRANSFER-CANCEL
      ueId:
        type: string
        description: Mobility Group UE identifier
      appState:
        $ref: '#/definitions/MobilityGroupAppState'
    description: Event object
  UeState:
    type: object
    properties:
      duration:
        type: integer
        description: Duration since the game stated
    description: Ue state basic information object
    example:
      ueState:
        - duration: 32
responses:
  Std200:
    description: OK
  Std201:
    description: Created
  Std202:
    description: Accepted
  Std204:
    description: No content
  Std304:
    description: Not modified
  Std400:
    description: Bad request
  Std401:
    description: Not authorized
  Std403:
    description: Forbidden
  Std404:
    description: Not found
  Std409:
    description: Conflict
  Std416:
    description: Requested range not satisfiable
  Std500:
    description: Internal server error
externalDocs:
  description: Find out more about MEEP Demo App API
  url: 'http://www.localinfo/pdf'
