apiVersion: v1
kind: Service
metadata:
  name: {{ template "meep-rnis.fullname" . }}
  labels:
    app: {{ template "meep-rnis.name" . }}
    chart: {{ template "meep-rnis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    meepOrigin: {{ .Values.meepOrigin }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "meep-rnis.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

