apiVersion: v1
kind: Service
metadata:
  name: {{ template "meep-rnis.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "meep-rnis.name" . }}
    chart: {{ template "meep-rnis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    meepOrigin: {{ .Values.meepOrigin }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "meep-rnis.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}

