{{- if .Values.persistentVolume.enabled}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: meep-pv-kibana
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: meep-pv-kibana
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{.Values.persistentVolume.location}}"
  storageClassName: meep-pv-kibana
{{- end }}
