# Default values for meep-loc-serv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
serviceAccount: meep-loc-serv

deployment:
  replicas: 1
  port: 80
  protocol: TCP

image:
  repository: meep-loc-serv
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  targetPort: 80
  nodePort: 30007

codecov:
  enabled: false

meepOrigin: core
