# Default values for meep-virt-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-virt-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-docker-registry:30001/meep-virt-engine
  tag: latest
  pullPolicy: Always      
  env:
    MEEP_HOST_URL: "http://www.example.com"

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  accessMode: 'ReadWriteOnce'
  reclaimPolicy: Retain
  size: 5Gi
  location: ''
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If set to "fullname", storageClassName: <template fullname>
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: '-'
  storageClass: 'fullname'

codecov:
  enabled: false
  
meepOrigin: core
