# Default values for meep-ctrl-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
serviceAccount: meep-virt-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-docker-registry:30001/meep-virt-engine
  tag: latest
  pullPolicy: Always      

service:
  type: ClusterIP
  port: 80

volumes:
  charts:
    path: <HOME>/.meep/charts

codecov:
  enabled: false
  
meepOrigin: core