# Default values for meep-rnis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
serviceAccount: meep-rnis

deployment:
  replicas: 1
  port: 80
  protocol: TCP

image:
  repository: meep-rnis
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  targetPort: 80
  nodePort: 30017

codecov:
  enabled: false

meepOrigin: core
