{{- if .Values.altService.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "meep-platform-ctrl.fullname" . }}-alt
  labels:
    app: {{ template "meep-platform-ctrl.name" . }}
    chart: {{ template "meep-platform-ctrl.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    meepOrigin: {{ .Values.meepOrigin }}
spec:
  type: {{ .Values.altService.type }}
  selector:
    app: {{ template "meep-platform-ctrl.name" . }}
    release: {{ .Release.Name }}
    meepOrigin: {{ .Values.meepOrigin }}
  ports:
    - port: {{ .Values.altService.port }}
      targetPort: {{ .Values.deployment.altPort }}
      {{- if .Values.altService.nodePort }}
      nodePort: {{ .Values.altService.nodePort }}
      {{- end }}
{{- end}}
