{{- if .Values.user.swagger.enabled}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: meep-platform-ctrl-user-swagger-pv
spec:
  storageClassName: meep-platform-ctrl-user-swagger-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.user.swagger.location }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: meep-platform-ctrl-user-swagger-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meep-platform-ctrl-user-swagger-pvc
spec:
  storageClassName: meep-platform-ctrl-user-swagger-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end}}
