apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: meep-webhook-cfg
webhooks:
  - name: meep-webhook.idcc.com
    clientConfig:
      service:
        name: meep-webhook
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXhPVEUwTWpnMU1Gb1hEVEk1TURNeE5qRTBNamcxTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGhTCkVGUVB1N2tPOTZSYk1lZUJQVmJCTGJTblFZeVNhMWc3Q0t4VGxLaXpvaXhtd1Q2c0d6MzdKdmhRZmVkWEVLMmkKeWNLQ2E0SzVsN21jUUhIckdlV3c2MmNvaCtQK2t5M2I1VG5YVjF0cnNlbUhEL3lLS0Ewd1l4eDRBQjc4TVg2aQo5K3ZMRzVxTVk5aTZtclhiaHQ2dVBTS1I0SG9LeEgvL2dyajg4Y1RHMDdiWjA2MXNlVEc0bzg4TEFSYVZZNzFjClNpZ2N6UlN0N3JMb1R6YkFqL1ZPRTVjZ1ZqSmZlOU5tUFFVTWJXY1VwZEpWTkV5c2xhK0JZU2hvRWlJcWdSOTgKNmQxVVorOGZIYWhXdC93RWZ3QjRIUDZuUHk4ZGxHSkFTY0UxNnl2V3FvenNkK2RDcEtTYlZiOXhGUDVLVFhCVQpGeUZrMUoxbkhuMEtUQkNZQ1BzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHYThKeUlRM1czaWdCVElYRHZUVldHMldaNnQKL0tLTDFFcWxFVVVFbWk4TkRPakljL0lSbnQrUTYyWitHOURHOEFNaU4wQUp5TFUyM0hUaTRRZEk5YW9ONVlwegoxNTFtZTJZM1BrQTZndXhYejQ5NW9wYUlsZ3lVbVAvdmo2d0pmc1NqMGE2UHVSamtQUnZwdFp3c2lmLy9VQ0ZPCnVzb3hFTW03QWU0UWZIekVWMjdobUdtd0Ewd3lPWDl5ci9yWnZ2bldtTmRsemlodU1lSm5TRGV5VzhQdC81MDAKOUN3Um1TWWdqenNjWHFjR2gwY25zcERBVlNncFRubEtBZ1luNXF4MHZ3RHVxK2R3R0p2Y3J3dDhjaUdsa1RmRAovRU4zNHczUVh0cWNFd0Nva1BoTTlSdE9CeFZOUDFUWjQvY3lKWG5QM0xPTm9McGVwbndzM2pLdU8vUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
