apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "meep-mg-manager.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "meep-mg-manager.name" . }}
    chart: {{ template "meep-mg-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    meepOrigin: {{ .Values.meepOrigin }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "meep-mg-manager.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ template "meep-mg-manager.name" . }}
        release: {{ .Release.Name }}
        meepOrigin: {{ .Values.meepOrigin }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- if .Values.codecov.enabled}}
      volumes:
        - name: codecov-storage
          persistentVolumeClaim:
            claimName: meep-mg-manager-codecov-pvc
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.codecov.enabled}}
          command: [ "/meep-mg-manager" ]
          args: [ "-test.coverprofile=/codecov/codecov-meep-mg-manager.out", "__DEVEL--code-cov" ]
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
              protocol: {{ .Values.deployment.protocol }}
          {{- if .Values.codecov.enabled}}
          volumeMounts:
          - name: codecov-storage
            mountPath: /codecov
          {{- end}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
