{{- if .Values.user.values.enabled}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: meep-virt-engine-user-values-pv
spec:
  storageClassName: meep-virt-engine-user-values-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.user.values.location }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: meep-virt-engine-user-values-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meep-virt-engine-user-values-pvc
spec:
  storageClassName: meep-virt-engine-user-values-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end}}
