{{- if .Values.letsEncrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsEncrypt.issuer }}
spec:
  acme:
    server: {{ .Values.letsEncrypt.acme.server }}
    email: AdvantEDGE@InterDigital.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
