{{- if .Values.letsEncrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsEncrypt.issuer }}
spec:
  acme:
    {{- if .Values.letsEncrypt.acme.prod }}
    server: {{ .Values.letsEncrypt.acme.prodServer }}
    {{- else }}
    server: {{ .Values.letsEncrypt.acme.stagingServer }}
    {{- end }}
    email: AdvantEDGE@InterDigital.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
