{{- if .Values.letsEncrypt.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "meep-ingress-certs.fullname" . }}-le
  labels:
    app: {{ template "meep-ingress-certs.name" . }}-le
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.letsEncrypt.issuer }}
spec:
  backend:
    serviceName: {{ .Values.letsEncrypt.defaultBackend.service.name }}
    servicePort: {{ .Values.letsEncrypt.defaultBackend.service.port }}
  tls:
    - secretName: {{ .Values.letsEncrypt.tls.secret }}
      hosts:
      - {{ .Values.letsEncrypt.tls.host }} 
{{- end }}
