swagger: '2.0'
info:
  version: 1.0.0
  title: MEEP Mobility Group Manager Model
  description: >
    Copyright (c) 2019  InterDigital Communications, Inc

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
definitions:
  MobilityGroup:
    type: object
    properties:
      name:
        type: string
        description: Mobility Group name
      stateTransferMode:
        type: string
        description: State Transfer mode
        enum:
          - STATE-DIRECT
          - STATE-MANAGED
          - INSTANCE-DIRECT
          - INSTANCE-MANAGED
          - NONE
      stateTransferTrigger:
        type: string
        description: State Transfer trigger
        enum:
          - NET-LOC-IN-RANGE
          - NET-LOC-CHANGE
          - GPS-PROXIMITY
          - NONE
      sessionTransferMode:
        type: string
        description: Session Transfer mode
        enum:
          - GRACEFUL
          - FORCED
      loadBalancingAlgorithm:
        type: string
        description: Load Balancing Algorithm
        enum:
          - HOP-COUNT
          - LATENCY
          - DISTANCE
    description: Mobility Group
  MobilityGroupApp:
    type: object
    properties:
      id:
        type: string
        description: Mobility Group Application Identifier
      url:
        type: string
        description: Event handler url
    description: Mobility Group Application instance
  MobilityGroupAppState:
    type: object
    properties:
      ueId:
        type: string
        description: Mobility Group UE Identifier
      ueState:
        type: string
        description: Mobility Group Application State for provided UE
    description: Mobility Group Application State
  MobilityGroupUE:
    type: object
    properties:
      id:
        type: string
        description: Mobility Group UE Identifier
    description: Mobility Group UE instance
  MobilityGroupEvent:
    type: object
    properties:
      name:
        type: string
        description: Mobility Group event name
      type:
        type: string
        description: Mobility Group event type
        enum:
          - STATE-UPDATE
          - STATE-TRANSFER-START
          - STATE-TRANSFER-COMPLETE
          - STATE-TRANSFER-CANCEL
      ueId:
        type: string
        description: Mobility Group UE identifier
      appState:
        $ref: '#/definitions/MobilityGroupAppState'
    description: Event object
  MobilityGroupServiceMap:
    type: object
    properties:
      mgSvcName:
        type: string
        description: Mobility group service name
      lbSvcName:
        type: string
        description: Load balanced service instance name
    description: Mobility group service mapping
  NetworkElementList:
    type: object
    properties:
      networkElements:
        type: array
        items:
          $ref: '#/definitions/NetworkElement'
    description: List of network element
  NetworkElement:
    type: object
    properties:
      name:
        type: string
        description: Network element name
      serviceMaps:
        type: array
        items:
          $ref: '#/definitions/MobilityGroupServiceMap'
    description: Network element service mappings
