---
swagger: "2.0"
info:
  description: "This API enables the WLAN Access Information Service to post notification\
    \ events to subscribers' applications <p>**Micro-service**<br>None <p>**Type &\
    \ Usage**<br>User's Edge Applications subscribing to WLAN Access Information events\
    \ must implement this API <p>**Details**<br>API details available at _your-AdvantEDGE-ip-address/api_\
    \ <p>**Note**<br>This API is not exposed by default on the AdvantEDGE platform"
  version: "1.0.0"
  title: "AdvantEDGE WLAN Access Information Service Subscription Notification REST\
    \ API"
  contact:
    name: "InterDigital AdvantEDGE Support"
    email: "AdvantEDGE@InterDigital.com"
  license:
    name: "Apache 2.0"
    url: "https://github.com/InterDigitalInc/AdvantEDGE/blob/master/LICENSE"
basePath: "/wai/v1"
tags:
- name: "notifications"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /notifications/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE WAI Service to issue a callback\
        \ notification"
      description: "Subscription notification"
      operationId: "postNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Notification"
        required: true
        schema:
          $ref: "#/definitions/Notification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
  /notifications/expiry/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE WAI Service to issue a notification\
        \ with regards to expiry of an existing subscription"
      description: "Subscription expiry notification"
      operationId: "postExpiryNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Subscription expiry Notification"
        required: true
        schema:
          $ref: "#/definitions/ExpiryNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
definitions:
  Link:
    type: "object"
    properties:
      self:
        type: "string"
        format: "uri"
        example: "http://meAppClient.example.com/wai/v1/1"
        description: "URI referring to a resource"
    description: "List of hyperlinks related to the resource"
    example:
      self: "http://meAppClient.example.com/wai/v1/1"
  TimeStamp:
    type: "object"
    required:
    - "nanoSeconds"
    - "seconds"
    properties:
      seconds:
        type: "integer"
        format: "uint32"
        example: 1577836800
        description: "The seconds part of the time. Time is defined as Unix-time since\
          \ January 1, 1970, 00:00:00 UTC"
      nanoSeconds:
        type: "integer"
        format: "uint32"
        example: 0
        description: "The nanoseconds part of the time. Time is defined as Unix-time\
          \ since January 1, 1970, 00:00:00 UTC"
    example:
      seconds: 1577836800
      nanoSeconds: 0
  ExpiryNotification:
    type: "object"
    required:
    - "_links"
    - "expiryDeadline"
    properties:
      timestamp:
        $ref: "#/definitions/TimeStamp"
      _links:
        $ref: "#/definitions/Link"
      expiryDeadline:
        $ref: "#/definitions/TimeStamp"
    example:
      _links:
        self: "http://meAppClient.example.com/wai/v1/1"
      expiryDeadline:
        seconds: 1577836800
        nanoSeconds: 0
      timestamp:
        seconds: 1577836800
        nanoSeconds: 0
  Notification:
    type: "object"
    required:
    - "notificationType"
    properties:
      notificationType:
        type: "string"
        description: "Notification type"
        enum:
        - "StaDataRateNotification"
        - "AssocStaNotification"
      timestamp:
        $ref: "#/definitions/TimeStamp"
      apId:
        $ref: "#/definitions/ApIdentity"
      staId:
        type: "array"
        items:
          $ref: "#/definitions/StaIdentity"
      staDataRate:
        type: "array"
        items:
          $ref: "#/definitions/StaDataRate"
    example:
      application/json:
        notificationType: "AssocStaNotification"
        timeStamp:
          seconds: 1577836800
          nanoSeconds: 0
        apId:
          macId: "11:22:33:44:55:66"
          ssid: "mySsid"
          ipAddress: "1.2.3.4"
  ApIdentity:
    type: "object"
    required:
    - "macId"
    properties:
      macId:
        type: "string"
        example: "11:22:33:44:55:66"
        description: "Identifier assigned to an Access Point for communications at\
          \ the data link layer of a network segment."
      ssid:
        type: "string"
        example: "mySsid"
        description: "Service set identifier to identify logical networks."
      ipAddress:
        type: "string"
        example: "1.2.3.4"
        description: "IPv4 or IPv6 address allocated to the Access Point."
  StaIdentity:
    type: "object"
    required:
    - "macId"
    properties:
      macId:
        type: "string"
        example: "11:22:33:44:55:66"
        description: "Identifier assigned to station for communications at the data\
          \ link layer of a network segment."
      ssid:
        type: "string"
        example: "mySsid"
        description: "Service set identifier to identify logical networks."
      aid:
        type: "string"
        example: "1234"
        description: "Number which identifies a particular association between a station\
          \ and Access Point."
      ipAddress:
        type: "string"
        example: "1.2.3.4"
        description: "IPv4 or IPv6 address allocated to a station."
  StaDataRate:
    type: "object"
    properties:
      staId:
        $ref: "#/definitions/StaIdentity"
      staLastDataDownlinkRate:
        type: "integer"
        format: "uint32"
        example: 1000
        description: "The data transmit rate in kbps that was most recently used for\
          \ transmission of data PPDUs from the access point to the station."
      staLastDataUplinkRate:
        type: "integer"
        format: "uint32"
        example: 1000
        description: "The data transmit rate in kbps that was most recently used for\
          \ transmission of data PPDUs from the associated station to the access point."
parameters:
  Path.SubscriptionId:
    name: "subscriptionId"
    in: "path"
    description: "Identity of a notification subscription"
    required: true
    type: "string"
    x-exportParamName: "SubscriptionId"
  Body.Notification:
    in: "body"
    name: "Notification"
    description: "Notification"
    required: true
    schema:
      $ref: "#/definitions/Notification"
    x-exportParamName: "Notification"
  Body.ExpiryNotification:
    in: "body"
    name: "Notification"
    description: "Subscription expiry Notification"
    required: true
    schema:
      $ref: "#/definitions/ExpiryNotification"
    x-exportParamName: "Notification"
externalDocs:
  description: "ETSI MEC028 V2.1.1 Radio Network Information Service API"
  url: "http://www.etsi.org/deliver/etsi_gs/MEC/001_099/028/02.01.01_60/gs_MEC028v020101p.pdf"
