---
swagger: "2.0"
info:
  description: "This is MEEP Location Services Notification Callback API"
  version: "0.0.0"
  title: "MEEP Location Service - Notification Callback"
  termsOfService: "InterDigital Internal Only"
host: "172.0.0.1:8081"
basePath: "/location/v1/"
tags:
- name: "notifications"
  description: "AdvantEDGE Location Subscription Notification Callbacks (user and\
    \ zonal)"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /location_notifications/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE Location Service to issue\
        \ a callback notification towards an ME application with a zonal or user tracking\
        \ subscription"
      description: "Zonal or User location tracking subscription notification"
      operationId: "TrackingNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription (user or zonal)"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Zonal or User Tracking Notification"
        required: true
        schema:
          $ref: "#/definitions/TrackingNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
  /zone_status_notifications/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE Location Service to issue\
        \ a callback notification towards an ME application with a zone status tracking\
        \ subscription"
      description: "Zone status tracking subscription notification"
      operationId: "ZoneStatusNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription (user or zonal)"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Zone Status Notification"
        required: true
        schema:
          $ref: "#/definitions/ZoneStatusNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
definitions:
  OperationStatus:
    type: "string"
    description: "The operation status of the access point"
    example: "Serviceable"
    enum:
    - "Serviceable"
    - "Unserviceable"
    - "Unknown"
  SubscriptionId:
    type: "string"
    description: "Unique Identifier for a notification subscription.  Created by the\
      \ MEC Location Service and used to reference an individual subscription"
    example: "sub123"
  UserInfo:
    type: "object"
    required:
    - "accessPointId"
    - "address"
    - "resourceURL"
    - "zoneId"
    properties:
      userId:
        type: "string"
        example: "client001"
        description: "Unique identifier of a user or client node"
      address:
        type: "string"
        format: "uri"
        example: "acr:192.0.2.1"
        description: "Address of user (e.g. \"sip\" URI, \"tel\" URI, \"acr\" URI)."
      accessPointId:
        type: "string"
        example: "001010000000000000000000000000001"
        description: "Identifier of access point, <E-CGI><Cell Portion ID> (reference\
          \ ETSI TS 129 171). Where the E-CGI is made up of the PLMN and Cell Identity\
          \ (28 bit string). Then the PLMN is made up of the 3 digit MCC & 2 or 3\
          \ digit MNC. The Cell Portion is an optional element"
      zoneId:
        type: "string"
        example: "zone01"
        description: "Identifier of zone"
      resourceURL:
        type: "string"
        format: "url"
        example: "http://localhost:8291/myService/123456"
        description: "URL where the UE may be contacted for some service (application\
          \ specific)"
  UserList:
    type: "object"
    required:
    - "userList"
    properties:
      userList:
        type: "array"
        items:
          $ref: "#/definitions/UserInfo"
  UserEventType:
    type: "string"
    enum:
    - "Entering"
    - "Transferring"
    - "Leaving"
  UserTrackingNotification:
    type: "object"
    required:
    - "callbackData"
    - "timeStamp"
    - "userInfo"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ ZonalTrafficSubscription and UserTrackingSubscription operation. See [REST_NetAPI_Common]."
      userInfo:
        $ref: "#/definitions/UserInfo"
      timeStamp:
        type: "string"
        format: "date-time"
        example: "2017-01-01T02:51:43Z"
        description: "Indicates the time of day for zonal presence notification."
      userEventType:
        $ref: "#/definitions/UserEventType"
    description: "User tracking notification - callback generated toward an ME app\
      \ with a user tracking subscription"
  ZoneInfo:
    type: "object"
    required:
    - "numberOfAccessPoints"
    - "numberOfUsers"
    - "zoneId"
    properties:
      zoneId:
        type: "string"
        example: "zone01"
        description: "Identifier of zone"
      numberOfAccessPoints:
        type: "integer"
        format: "uint32"
        example: 10
        description: "Number of access points or points of access within a Location\
          \ Zone"
      numberOfUsers:
        type: "integer"
        format: "uint32"
        example: 7
        description: "The number of users currently on the access point"
    description: "A type containing zone information."
  ZoneStatusNotification:
    type: "object"
    required:
    - "timestamp"
    - "zoneId"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ ZonalTrafficSubscription and UserTrackingSubscription operation. See [REST_NetAPI_Common]."
      zoneId:
        type: "string"
        example: "zone01"
        description: "Identifier of zone"
      accessPointId:
        type: "string"
        example: "001010000000000000000000000000001"
        description: "Identifier of access point, <E-CGI><Cell Portion ID> (reference\
          \ ETSI TS 129 171). Where the E-CGI is made up of the PLMN and Cell Identity\
          \ (28 bit string). Then the PLMN is made up of the 3 digit MCC & 2 or 3\
          \ digit MNC. The Cell Portion is an optional element"
      numberOfUsersInZone:
        type: "integer"
        format: "uint32"
        example: 20
        description: "This element shall be present when ZoneStatusSubscription includes\
          \ numberOfUsersZoneThreshold element and the number of users in a zone exceeds\
          \ the threshold defined in this subscription."
      numberOfUsersInAP:
        type: "integer"
        format: "uint32"
        example: 12
        description: "This element shall be present when ZoneStatusSubscription includes\
          \ numberOfUsersAPThreshold element and the number of users in an access\
          \ point exceeds the threshold defined in the subscription."
      operationStatus:
        $ref: "#/definitions/OperationStatus"
      timestamp:
        type: "string"
        format: "date-time"
        example: "2017-01-01T02:51:43Z"
        description: "Indicates the time of day for zonal presence notification."
      link:
        type: "array"
        example: "rel=\"ZonalStatusSubscription\" href=\"http://example.com/exampleAPI/location/v1/subscriptions/zonalStatus/sub123\""
        description: "Link to other resources that are in relationship with this notification.\
          \ The server SHOULD include a link to the related subscription. No other\
          \ links are required or suggested by this specification."
        items:
          $ref: "#/definitions/Link"
    description: "A type containing zone status notification."
    example:
      operationStatus: "Serviceable"
      callbackData: "1234"
      accessPointId: "001010000000000000000000000000001 or poa001"
      link: "rel=\"ZonalStatusSubscription\" href=\"http://example.com/exampleAPI/location/v1/subscriptions/zonalStatus/sub123\""
      zoneId: "zone001"
      numberOfUsersInZone: "20"
      numberOfUsersInAP: "12"
      timestamp: "2017-01-01T02:51:43Z"
  TrackingNotification:
    type: "object"
    required:
    - "callbackData"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ ZonalTrafficSubscription and UserTrackingSubscription operation. See [REST_NetAPI_Common]."
      zoneId:
        type: "string"
        example: "zone01"
        description: "Identifier of zone"
      address:
        type: "string"
        format: "uri"
        example: "acr:192.0.2.1"
        description: "Address of user (e.g. \"sip\" URI, \"tel\" URI, \"acr\" URI)."
      interestRealm:
        type: "string"
        example: "LA"
        description: "Interest realm of access point (e.g. geographical area, a type\
          \ of industry etc.)."
      userEventType:
        $ref: "#/definitions/UserEventType"
      currentAccessPointId:
        type: "string"
        example: "zone01"
        description: "Zone ID"
      previousAccessPointId:
        type: "string"
        example: "zone02"
        description: "Zone ID"
      timestamp:
        type: "string"
        format: "date-time"
        example: "2017-01-01T02:51:43Z"
        description: "Indicates the time of day for zonal presence notification."
    description: "Zonal or User tracking notification - callback generated toward\
      \ an ME app with a zonal or user tracking subscription"
    example:
      address: "acr:10.1.34.67"
      userEventType: {}
      callbackData: "1234"
      previousAccessPointId: "001010000000000000000000000000001 or poa001"
      zoneId: "zone001"
      interestRealma: "NY"
      currentAccessPointId: "001010000000000000000000000000001 or poa001"
      timestamp: "2017-01-01T02:51:43Z"
parameters:
  Path.SubscriptionId:
    name: "subscriptionId"
    in: "path"
    description: "Identity of a notification subscription (user or zonal)"
    required: true
    type: "string"
    x-exportParamName: "SubscriptionId"
  Body.TrackingNotification:
    in: "body"
    name: "Notification"
    description: "Zonal or User Tracking Notification"
    required: true
    schema:
      $ref: "#/definitions/TrackingNotification"
    x-exportParamName: "Notification"
  Body.ZoneStatusNotification:
    in: "body"
    name: "Notification"
    description: "Zone Status Notification"
    required: true
    schema:
      $ref: "#/definitions/ZoneStatusNotification"
    x-exportParamName: "Notification"
externalDocs:
  description: "Find out more about MEC Location Services"
  url: "http://www.etsi.org/deliver/etsi_gs/MEC/001_099/013/01.01.01_60/gs_MEC013v010101p.pdf"
